### ISSUE TITLE
Build show blank page

### ISSUE THREAD

**Issue by nas-me** [FractalHQ/sveltekit-electron#1]
Hello,

I tested the project in two different machines (osx catalina and debian 10)

Dev is working Well in both.

I added electron-window-start as a dependencie to start the build (without errors).

Now i'm having a blank screen with the mac build because the http server is not started and .deb packet manager window disapear if trying to install.

**Comment by FractalHQ** [comment]
I've got a new branch going to play with this.  I had to move a few devDeps to deps like you said, and the build errors are gone, but I also can't seem to get the window to render.  I've been digging around and tweaking the build for a couple hours now with no luck.

One thing I noticed is that after the Sveltekit build, the build dir doesn't seem to include an index.html (or any html) file.  Bit of a head scratcher.

Have you made any progress?

**Comment by jinxmcg** [comment]
I think because by default SvelteKit is SSR this means there is a "server" which needs to be started and then the window must point to localhost/port or make the build SPA/Static

**Comment by nas-me** [comment]
@FractalHQ I didn't try yet, but will surely dig in when i'll have some time.

@jinxmcg you are right about the index.html that can't be found, i tested with other path than localhost/port on package.json.

It can also be Vite related configuration in electron.js 
(same behavior with react + Electron + Vite)

**Comment by FractalHQ** [comment]
@jinxmcg you're a legend!  Seems to be working out great.  @nas-me does this fix work on your linux machine?

**Comment by nas-me** [comment]
@FractalHQ it works like charms with npm run build !

Thank you, that was fast (i was planing with your fix-build and @jinxmcg code)

For you last version, pnpm give me jsonfile error but maybe it is related to my local setup.

@jinxmcg thank you for the SPA / SSR advise about electron.

**Comment by jinxmcg** [comment]
Happy to help.

@FractalHQ just noticed that now you use adapter-static for svelte-kit, this means that you do not need to fork anything because you get the index.html which you already serve with electron-serve, also feel free to leave the app with ASAR enabled in this case.

Fork is only needed if you have your svelte app as a SSR using adapter-node and need to start the node server from index.js. Then for this you have to disable ASAR (fork does not work well with asar enabled)

Maybe a config flag could be used to start sveltekit-electron as SSR version with fork or as Static version which uses electron-serve and index.html

I do not see a big advantage of SSR when doing electron apps. So my advice would be just focusing on adapter-static + asar enabled + electron-serve.

**Comment by FractalHQ** [comment]
@jinxmcg This is great advice- I decided to go with the static approach. Thanks again!!  You're awesome.

Also @nas-me thanks for pointing out the issue with pnpm!  I had the same problem.  It seems like the node modules fail to be bundled when building with pnpm.  I added a notice ￼to the README for others.
